### ISSUE TITLE
Old heartbeat items are not cleared from local storage

### ISSUE THREAD

**Issue by tomas-c** [aermin/web-locks#38]
Hey @aermin,

Nice work on the library! I've been testing this out and noticed that for every browser tab refresh, a new item gets added to local storage.

![image](https://user-images.githubusercontent.com/5213953/133668805-679eee3c-84c8-4970-9350-ab8951e910c0.png)

I thought about a potential fix, and looking through the code I see there is an "unload" handler in `heartBeat.ts` that could be modified to clear the heartbeat item. However, "unload" events are not reliably fired in many browsers so might need to think of something else.

**Comment by tomas-c** [comment]
Another idea I had, is cleaning up the old values on initialisation rather than on closing:

1. Prefix the heartbeat item keys with a known constant value.
2. Whenever LockManager is created, iterate over all Local Storage items, and clear the ones that start with the prefix and have a timestamp that is old (wouldn't want to delete active heartbeats items from another tab).

**Comment by aermin** [comment]
Hi @tomas-c , thx your detailed testing, feedback, and advice ，It is very helpful!

this issue is because  I clean the old, useless heartbeat key by the ids which calculate from query(), It only returns the locks' client ids, It is wrong, the heartbeat keys from the non-locks client should also be clean when destroying this client.

This the fix Mr, pls help to review ^ ^
https://github.com/aermin/web-locks/pull/39

thx ^ ^

**Comment by aermin** [comment]
> Another idea I had, is cleaning up the old values on initialisation rather than on closing:
> 
> 1. Prefix the heartbeat item keys with a known constant value.
> 2. Whenever LockManager is created, iterate over all Local Storage items, and clear the ones that start with the prefix and have a timestamp that is old (wouldn't want to delete active heartbeats items from another tab).

the diff is I use a locally stored array to record the client ids, then iterate this array, detect it, clean the useless ones.
```
clear the ones that start with the prefix
```
If clear the ones that start with the prefix, It is well, but afraid clear the same prefix's storage key of the app  eventuality

**Comment by tomas-c** [comment]
The reason why I suggested the prefix if not to avoid collisions with different apps. It's to avoid having shared array of all clientIds that can be corrupted due to two clients doing overlapping read-write operations.

The prefix allows you to find out all clientIds by doing this `Object.keys(localStorage).filter(it => it.startsWith(PREFIX))` without the need for a shared array that can be corrupted.

**Comment by aermin** [comment]
yep, I got you mean, I just concern about the developer use the same PREFIX  as storage key PREFIX, and we clear it by mistake😢
```
Object.keys(localStorage).filter(it => it.startsWith(PREFIX))
```

**Comment by aermin** [comment]
> I have tested the storage reading and writing operation spending time, It is very fast, millisecond-level. In my testing, do getItem JSON.Parse JSON.Stringfy setItem , which for reading and writing, complete among 1 millisecond.
So when we reopen the tabs, it is not the real millisecond-level same time.

So It looks fine for this case:
> having shared array of all clientIds that can be corrupted due to two clients doing overlapping read-write operations.

**Comment by aermin** [comment]
> yep, I got your mean, I just concern about the developer use the same PREFIX as storage key PREFIX, and we clear it by mistake😢
> 
> ```
> Object.keys(localStorage).filter(it => it.startsWith(PREFIX))
> ```

But it may be difficult to happen if ignore it, indeed your suggestion would be better🤔 Let me think again 

@unadlib do you have any idea?

**Comment by tomas-c** [comment]
My suggested option only makes sense if you care about preventing inconsistencies due to overlapping read-write operations. If the rest of the code doesn't address that (e.g. _cleanClientLocksByClientId remains as it is), then maybe it's not worth to do it here and it's fine to keep your PR as it is.

**Comment by aermin** [comment]
> My suggested option only makes sense if you care about preventing inconsistencies due to overlapping read-write operations. If the rest of the code doesn't address that (e.g. _cleanClientLocksByClientId remains as it is), then maybe it's not worth to do it here and it's fine to keep your PR as it is.

Yep, if change according to you proposal, then `_cleanClientLocksByClientId` should also be prevented.

**Comment by aermin** [comment]
> _cleanClientLocksByClientId

by seems 

> > My suggested option only makes sense if you care about preventing inconsistencies due to overlapping read-write operations. If the rest of the code doesn't address that (e.g. _cleanClientLocksByClientId remains as it is), then maybe it's not worth to do it here and it's fine to keep your PR as it is.
> 
> Yep, if change according to you proposal, then `_cleanClientLocksByClientId` should also be prevented.

And seems it hard to find another way this instead of _cleanClientLocksByClientId implement. We have to modify the same storage value to implement the locks.
