### ISSUE TITLE
DOMException: Lock broken by another request with the 'steal' option.

### ISSUE THREAD

**Issue by cheater** [aermin/web-locks#46]
This error happens randomly, and the code acquiring the lock just blows up. This is in Firefox 91.

**Comment by aermin** [comment]
Hi @cheater, It follows the [Specification](https://wicg.github.io/web-locks/)
![image](https://user-images.githubusercontent.com/24861316/179386483-10810d5d-573b-4f1d-b69c-ee69cb0f9d24.png)
If you try chrome with native web lock API, you will find It also throws this error 
![image](https://user-images.githubusercontent.com/24861316/179386503-4ca5788b-dcdf-4cb7-959f-3cfee5d1f1a1.png)
and you could catch this promise error.

the test case from [web-platform-tests](https://github.com/web-platform-tests/wpt/blob/master/web-locks/steal.tentative.https.any.js): 
![image](https://user-images.githubusercontent.com/24861316/179386609-98d0effd-dfe4-47e6-981e-748dcac2bb45.png)

the test case from this project https://github.com/aermin/web-locks/blob/main/test/steal.test.ts

<img width="682" alt="image" src="https://user-images.githubusercontent.com/24861316/179386721-07ffc734-853b-4029-b1b2-897dd22ac23b.png">

**Comment by cheater** [comment]
I was getting this error with steal unspecified (which should make it false), but then I set steal explicitly to false, and I'm still getting this.

**Comment by cheater** [comment]
This is what the code looks like: `navigator.locks.request("my_resource", {steal: false}, async (lock) => {`

**Comment by aermin** [comment]
I test according to your description, but  It is fine.

<img width="2143" alt="image" src="https://user-images.githubusercontent.com/24861316/179443272-10fee951-3af4-4032-8159-300be253ead3.png">

test online:
 https://codesandbox.io/s/web-locks-demo-forked-sg9tkr?file=/src/App.tsx:1218-1227
 
 could you help check my testing step?

**Comment by cheater** [comment]
It's only intermittent.

What browser have you tested under?

**Comment by cheater** [comment]
I'm not sure how to help you test it - I'm a programmer but I'm unsure what you'd like me to do. Let me know of the steps you'd like me to perform.

A little bit about my code. Right after acquiring the lock, I create a Promise, to keep the lock around, like this: https://pastebin.com/tYMvDYGP

**Comment by cheater** [comment]
BTW, please test under Tor Browser

**Comment by aermin** [comment]
I testing under firefox
![image](https://user-images.githubusercontent.com/24861316/179666995-b1a0aaa5-42e0-44b3-835d-385e5ab1b74d.png)

and test with the code like yours, It also could not get the issue you say.
![image](https://user-images.githubusercontent.com/24861316/179667130-3e78d22c-ff7d-4524-a55a-7e759e0199bb.png) 

could you pls try to clean your localstorage and test again?
and `{steal: false}` is not need to write, you could remove it, It equal to the default options.

**Comment by aermin** [comment]
Oh, I just learned about Tor Browser. Sorry, this polyfill is just for the major old version browsers like Firefox, Safari. 😂

**Comment by cheater** [comment]
Tor Browser is Firefox 91 with some additions. It is a major browser. Please reopen the bug report.

**Comment by cheater** [comment]
Also, btw, that version of Tor has 2 million users, it's hardly a fringe use case.

**Comment by aermin** [comment]
I download Tor Browser and ran the web lock test app under it, but could not find the issue. https://github.com/aermin/web-lock-test/blob/master/src/App.tsx
Could you pls pull this test project in your local and edit the code, and run it to test. If could recurrent the issue, pls create a test code mr, and I will debug with it. Is it ok?
